spring:
  application:
    name: payment-service

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://127.0.0.1:5432/payment_platform}
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD:payment_password}
    pool:
      initial-size: 10
      max-size: 20

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    payment-created-events-topic: ${PAYMENT_CREATED_EVENTS_TOPIC:payment-created-events-topic}

integration:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8090/api/accounts}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8887/eureka/}
  instance:
    prefer-ip-address: true

server:
  port: 8091