spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    secure-port-enabled: true
    secure-port: 443
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8887/eureka/}

server:
  port: 8887