spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${MONGO_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: true
      group-id: notification-service-group
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      missing-topics-fatal: false

kafka:
  topics:
    transaction-created-events-topic: transaction-created-events-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8095
