spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongo_user}:${MONGO_PASSWORD:mongo_password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:notification_db}?authSource=${MONGO_AUTH_DB:admin}
      database: ${MONGO_DATABASE:notification_db}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: true
      group-id: notification-service-group
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      missing-topics-fatal: false
  cloud:
    stream:
      bindings:
        notificationProcessor-in-0:
          destination: notifications
          content-type: application/json
        notificationProcessor-out-0:
          destination: processed-notifications
          content-type: application/json

kafka:
  topics:
    transaction-created-events-topic: transaction-created-events-topic

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8887/eureka/}

server:
  port: 8095
